[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
liqidator = "7EbEtVWNkof8HCnwTKyV8nxm3XzpPChkgD7Asj8P4Rzt"
order-book = "HeMJbjyq4hDeEykL6vEfs3x4jKrQBiXEkZ3yYp64KmvP"
position-router = "5dqPayZ7oyCMtEsZjSJyPW3sPHm36572Pg8SreDwMf3e"
router = "8HDnuc7AGaKUNCtSwiqb5H8wKsfjMUW7WpgZgS17VYAT"
solana_dex_anchor = "FQExbwU6c7DTUmMSmvHhiBw7zHiVWhEr1VR5zhHWbzCi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anjanay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
